spring.datasource.url=jdbc:postgresql://localhost:5432/myeconomy
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always

server.port=8080

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG


spring.application.name=demo
cors.allowed.origins=http://localhost:3000,http://localhost:4200,http://localhost:8081,http://10.0.2.2:8081
app.jwt.secret=mySecretKeyForJWTTokenGeneration2026SpringBootApplicationWithLongerStringForSecurity512Bits
app.jwt.expiration=86400000
