spring.application.name=demo
cors.allowed.origins=http://localhost:3000,http://localhost:4200,http://localhost:8081,http://10.0.2.2:8081
app.jwt.secret=mySecretKeyForJWTTokenGeneration2026SpringBootApplicationWithLongerStringForSecurity512Bits
app.jwt.expiration=86400000
